### ISSUE TITLE
UDP API Data Output

### ISSUE THREAD

**Issue by vinaysraghavan** [unicorn-bi/Unicorn-Suite-Hybrid-Black#10]
Is there any documentation about how to interpret the output from the UDP API? I have the API working and sending data to an outside program, but I can't figure out how to interpret the values I'm receiving. I'm getting 68 uint8 values, some which change quickly and others which change slowly, if at all.

**Comment by unicorn-bi** [comment]
Yes you are receiving 68 bytes because udp sends byte wise. These 68 bytes are 17 float channels. 1 float value is represented as 4 bytes. 17 channels x 4 bytes -> 68 byte values. To convert it back you have to  write these 4 bytes to a 32 bit vatiable and interpret it as single/float32. You can take the counter channel to check whether you are converting correctly or not. It should be incremented by one with every received scan. The 17 channels are arranged as following: EEG (1-8), accelerometer (9-11), gyroscope (12-14), counter (15), battery level (16), and validation indicator (17).
