### ISSUE TITLE
Online access to data samples

### ISSUE THREAD

**Issue by moeinrazavi** [unicorn-bi/Unicorn-Suite-Hybrid-Black#3]
I used the python API provided with Unicorn, but I can't record and show the data in online mode and it only saves data in offline mode which is the same as Unicorn Recorder. Could you please tell me how I should make changes so that it can record and show data in online mode?

I’ve already tried using python libraries but didn’t succeed. I need to have access to data samples in online mode for online processing as well. It seems like that the current python API only holds data in the buffer and then saves it on hard disk. I can’t have access to each time sample as they are being recorded online. Do you have any available python demo or example for that?

Thank you

**Comment by unicorn-bi** [comment]
Hello,
data acquisition using Unicorn Python API is working as following
1. after opening a device you can set it into acquisition mode using the "StartAcquisition" command
2. afterwards the Unicorn is set into acquisition mode and is continuously sending data
3. data can be received in online by calling "GetData" continously. The GetData command is blocking until the requested amount of data is available. Data is written a buffer array. Call GetData as long as you want to receive data in a loop to receive data in "realtime".
4. a data acquisition can be terminated by calling "StopAcquisition"

more details are available in the usermanual at "15.3. USING THE UNICORN PYTHON API" and "15.5. COMMAND ORDER"

in the example this sequence is executed; whenever data is available it is written into a file (in one example into a binary file in the other into a csv). It is written in "realtime" into the file. So if you want to access data online you have to add your code after every GetData call. Just keep in mind that the code you are adding/executing must execute faster than data is coming in, otherwise you will get acquisition errors, delays etc. If you need to execute slow code fragments you have to take more care about the timing and might have to apply more advanced techniques like multithreading, buffering and synchronization.

**Comment by mrf3137** [comment]
> Hello,
> data acquisition using Unicorn Python API is working as following
> 
> 1. after opening a device you can set it into acquisition mode using the "StartAcquisition" command
> 2. afterwards the Unicorn is set into acquisition mode and is continuously sending data
> 3. data can be received in online by calling "GetData" continously. The GetData command is blocking until the requested amount of data is available. Data is written a buffer array. Call GetData as long as you want to receive data in a loop to receive data in "realtime".
> 4. a data acquisition can be terminated by calling "StopAcquisition"
> 
> more details are available in the usermanual at "15.3. USING THE UNICORN PYTHON API" and "15.5. COMMAND ORDER"
> 
> in the example this sequence is executed and whenever data is available it is written into a file (in one example into a binary file in the other into a csv). It is written in "realtime" into the file. So if you want to access data online you have to add your code after every GetData call. Just keep in mind that the code you are adding/executing must execute faster than data is coming in, otherwise you will get acquisition errors, delays etc. If you need to execute slow code fragments you have to take more care about the timing and might have to apply more advanced techniques like multithreading, buffering and synchronization.

Say I want to just print the data in python console. When I do as showed in the following picture, the output is "None":
![image](https://user-images.githubusercontent.com/36338609/59135713-965df700-8945-11e9-92ff-8748b717ebe8.png)

**Comment by mrf3137** [comment]
Can you give me a sample code which can do something similar to what I need?

Thank you

**Comment by unicorn-bi** [comment]
Sorry, I don’t have an example in python. I’d start with the examples and reverse engineer/understand the examples and then modify them. You could e.g. make the example threaded etc. 

 

For the things you are planning to do, you should research the following topics/concepts:

*	Thread synchronization
*	Parallel computing
*	Pipe and filter pattern (also called pipeline or signal processing chain)

 

You can also try to interface python libraries that implement these techniques already. Like https://github.com/bbci/wyrm (but I don’t know if this library supports python 3 already).

 

Best,




 

Martin Walchshofer, MSc | Software Engineer
g.tec medical engineering GmbH 
Sierningstrasse 14 | 4521 Schiedlberg | Austria
office: +43 <tel:0043725122240>  7251 22240
email: w <mailto:walchshofer@gtec.at%20> alchshofer@gtec.at  

 

w: www.gtec.at <http://www.gtec.at> 

b: blog.gtec.at <http://blog.gtec.at/> 

f: g.tec medical engineering <https://www.facebook.com/gtecmedical> 

t: @gtec_BCI <https://twitter.com/gtec_BCI> 
y: gtec medical engineering <https://www.youtube.com/channel/UCVR80bpCIQyWgyGa20OLmvw> 
l: g.tec medical engineering GmbH <https://www.linkedin.com/company/1627233/>
